name: Feature Request
description: Request a new feature
labels: [ "enhancement", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request and document this new feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A concise description of the problem you need this new feature to solve.
      placeholder: What is the problem you are trying to solve...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description of the new feature you need.
      placeholder: What will this new feature do, how will it work...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any other alternatives you considered.
      placeholder: Other ways you considered to solve your problem...
    validations:
      required: false
