name: Test JVM
on:
  push:
    paths:
      - "bdk-ffi/**"
      - "bdk-jvm/**"
  pull_request:
    paths:
      - "bdk-ffi/**"
      - "bdk-jvm/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            bdk-ffi/target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Build bdk-jvm library
        run: |
          cd bdk-jvm
          ./gradlew buildJvmLib

      - name: Run JVM tests
        run: |
          cd bdk-jvm
          ./gradlew test --console=rich
